### ISSUE TITLE
App Store Connect Erros

### ISSUE THREAD

**Issue by Roberdan** [ABTSoftware/SciChart-SP#1]
hi, I'm using latest package 4.1.0 and when trying to upload my app to the AppStore, I get those 2 errors. 
Do you have any idea how it could be solved? thx in advance.

1. App Store Connect Operation Error - Invalid directory. The bundle Payload/my appname.app/watch/SciChart.framework contained in a correctly named directory. It should be under "Frameworks"

2. App Store Connect Operation Error - CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.scichart' under the iOs application 'myappname.app'

PS: note I've both the iPhone and the watch apps, but SciChart is used only on the iPhone version.

Thanks in advance

Update: just tried to integrate SciChart manually and it works, so maybe it's something on the package itself?

**Comment by Roberdan** [comment]
pinging @SciChartTeam to see if they have any suggestion on this issue. thanks in advance, RD

**Comment by andyb1979** [comment]
Hello Rob,

Let me loop in the scichart ios team. I think we resolved this internally
but have not yet published.

Best regards,
Andrew

**Comment by Roberdan** [comment]
Thanks as usual and in advance folks!
One of your many fan!

Da: andyb1979 <notifications@github.com>
Data: martedì, 24 novembre 2020 19:18
A: ABTSoftware/SciChart-SP <SciChart-SP@noreply.github.com>
Cc: Roberto D'Angelo <roberdan@fightthestroke.org>, Author <author@noreply.github.com>
Oggetto: Re: [ABTSoftware/SciChart-SP] App Store Connect Erros (#1)
Hello Rob,

Let me loop in the scichart ios team. I think we resolved this internally
but have not yet published.

Best regards,
Andrew

**Comment by andyb1979** [comment]
Hi Roberdan, 

It appears to be an issue in Swift Package Manager, and we've already submitted an issue to Apple. Will notify you when there is a workaround or solution. 

Best regards, 
Andrew

**Comment by Roberdan** [comment]
Thanks!


Da: andyb1979 <notifications@github.com>
Data: martedì, 24 novembre 2020 19:54
A: ABTSoftware/SciChart-SP <SciChart-SP@noreply.github.com>
Cc: Roberto D'Angelo <roberdan@fightthestroke.org>, Author <author@noreply.github.com>
Oggetto: Re: [ABTSoftware/SciChart-SP] App Store Connect Erros (#1)

Hi Roberdan,

It appears to be an issue in Swift Package Manager, and we've already submitted an issue to Apple. Will notify you when there is a workaround or solution.

Best regards,
Andrew

**Comment by Roberdan** [comment]
hi there @SciChartTeam,  any update on this issue? thanks, RD

**Comment by andyb1979** [comment]
Hi Roberdan,

still awaiting an update from Apple I'm afraid ... issue is with Swift
package manager on their side :(

**Comment by Roberdan** [comment]
Hi @andyb1979 do they have an ETA, or the suggestion is to go with pods still for a while? Thanks, r.

**Comment by andyb1979** [comment]
Hi @Roberdan, as far as I know, no. team is aware of this issue + also that users such as yourself are waiting on it. We would suggest to use Cocoapod for now and as soon as we have Swift PM issue resolved we will notify you

Best regards
Andrew

**Comment by Roberdan** [comment]
just pinging if any luck before xmas on this subject? thx

**Comment by nrudnyk** [comment]
Hello @Roberdan,

Looks that potentially there could be a luck. We've published a fix in our nightly build, which is available via `4484892fb0a870aca20d16dab0188058ba936638` commit hash. 

Please see how to get nightly builds from SwiftPM in our documentation here: https://www.scichart.com/documentation/ios/current/integrating-scichart-libraries.html#integrating-scichart-strong-nightly-strong-builds-via-swiftpm

Please let us know if that helped.

Best Regards,
Nazar

**Comment by Roberdan** [comment]
hy @nrudnyk, unfortunately when uploading to the store, it still have the same issue :( One specific thing I noticed is that I have also the watch app and it seems it tries to duplicate the scichart library even if it's not used on the watch app.
if you want I can share the full log, just send me an email via roberdan (at) fightthestroke.org

thanks, RD

**Comment by Roberdan** [comment]
@nrudnyk found it. It duplicates the framework code into the watch app structure. If manually removed the duplication from the archive file then it all works. From a pure package perspective I think we can close this issue. Still for your info, in case it's an iOS and watch app someone can incur on the same issue. I will try to create a build script later today and if you want I'll share back if it will work. thanks so far! Merry Xmas to you all!

**Comment by nrudnyk** [comment]
@Roberdan great, thanks for the quick update.
Sure, please share that script at least for the sake of community.
Thanks and have a nice holidays.
Merry Christmas!
